/**
 * car_rental_backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Car } from './car';
import { Rating } from './rating';
import { BookingStatus } from './bookingStatus';
import { Location } from './location';


export interface Booking { 
    id?: number;
    name: string;
    lastName: string;
    email: string;
    phone: string;
    startDate: string;
    endDate: string;
    createdAt: string;
    lastUpdate?: string;
    bookingStatus: BookingStatus;
    total: number;
    ratingId?: number;
    rating?: Rating;
    carId?: number;
    car: Car;
    userId?: number;
    pickupLocationId?: number;
    pickupLocation: Location;
    dropOffLocationId?: number;
    dropOffLocation: Location;
}



