/**
 * car_rental_backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum Brand {
    AlfaRomeo = 'ALFA_ROMEO',
    Audi = 'AUDI',
    Bmw = 'BMW',
    Bugatti = 'BUGATTI',
    Ferrari = 'FERRARI',
    Fiat = 'FIAT',
    Ford = 'FORD',
    MercedesBenz = 'MERCEDES_BENZ',
    Toyota = 'TOYOTA',
    Volkswagen = 'VOLKSWAGEN'
}

