/**
 * car_rental_backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Brand = 'ALFA_ROMEO' | 'AUDI' | 'BMW' | 'BUGATTI' | 'FERRARI' | 'FIAT' | 'FORD' | 'MERCEDES_BENZ' | 'TOYOTA' | 'VOLKSWAGEN';

export const Brand = {
    AlfaRomeo: 'ALFA_ROMEO' as Brand,
    Audi: 'AUDI' as Brand,
    Bmw: 'BMW' as Brand,
    Bugatti: 'BUGATTI' as Brand,
    Ferrari: 'FERRARI' as Brand,
    Fiat: 'FIAT' as Brand,
    Ford: 'FORD' as Brand,
    MercedesBenz: 'MERCEDES_BENZ' as Brand,
    Toyota: 'TOYOTA' as Brand,
    Volkswagen: 'VOLKSWAGEN' as Brand
};

