/**
 * car_rental_backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Brand } from './brand';
import { Insurance } from './insurance';
import { Color } from './color';
import { Mileage } from './mileage';
import { Transmission } from './transmission';
import { CarLocation } from './carLocation';
import { FuelType } from './fuelType';


export interface Car { 
    id?: number;
    model: string;
    brand: Brand;
    engine: string;
    fuelType: FuelType;
    doors: number;
    color: Color;
    transmission: Transmission;
    mileage: Mileage;
    insurance: Insurance;
    seats: number;
    minimumDays: number;
    maximumDays: number;
    babySeats: number;
    year: number;
    licencePlate: string;
    price: number;
    averageRating?: number;
    reviewsCount?: number;
    createdAt: string;
    lastUpdate?: string;
    luggage: number;
    options?: string;
    imageUrl?: string;
    imagePublicId?: string;
    businessId: number;
    carLocations?: Array<CarLocation>;
}



