/**
 * car_rental_backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Brand } from './brand';
import { Color } from './color';
import { Transmission } from './transmission';
import { FuelType } from './fuel-type';


export interface Car { 
    id?: number;
    model: string;
    brand: Brand;
    engine: string;
    fuelType: FuelType;
    doors: number;
    color: Color;
    transmission: Transmission;
    seats: number;
    year: number;
    licencePlate: string;
    price: number;
    averageRating?: number;
    reviewsCount?: number;
}
export namespace Car {
}


