/**
 * car_rental_backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Color = 'BEIGE' | 'BLACK' | 'CHROME' | 'GRAY' | 'GREEN' | 'RED' | 'YELLOW' | 'WHITE';

export const Color = {
    Beige: 'BEIGE' as Color,
    Black: 'BLACK' as Color,
    Chrome: 'CHROME' as Color,
    Gray: 'GRAY' as Color,
    Green: 'GREEN' as Color,
    Red: 'RED' as Color,
    Yellow: 'YELLOW' as Color,
    White: 'WHITE' as Color
};

