/**
 * car_rental_backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type FuelType = 'ELECTRIC' | 'GAS' | 'GASOLINE' | 'GASOLINE_GAS' | 'PETROL';
export const FuelType = {
  Electric: 'ELECTRIC' as FuelType,
  Gas: 'GAS' as FuelType,
  Gasoline: 'GASOLINE' as FuelType,
  GasolineGas: 'GASOLINE_GAS' as FuelType,
  Petrol: 'PETROL' as FuelType
};

export const FuelTypeDisplayNames = {
  'ELECTRIC': 'Electric',
  'GAS': 'Gas',
  'GASOLINE': 'Gasoline',
  'GASOLINE_GAS': 'Gasoline + Gas',
  'PETROL': 'Petrol'
}

