export * from './bookingEndpoint.service';
import { BookingEndpointService } from './bookingEndpoint.service';
export * from './bookingEndpoint.serviceInterface';
export * from './businessEndpoint.service';
import { BusinessEndpointService } from './businessEndpoint.service';
export * from './businessEndpoint.serviceInterface';
export * from './carEndpoint.service';
import { CarEndpointService } from './carEndpoint.service';
export * from './carEndpoint.serviceInterface';
export * from './carLocationEndpoint.service';
import { CarLocationEndpointService } from './carLocationEndpoint.service';
export * from './carLocationEndpoint.serviceInterface';
export * from './favouriteBusinessEndpoint.service';
import { FavouriteBusinessEndpointService } from './favouriteBusinessEndpoint.service';
export * from './favouriteBusinessEndpoint.serviceInterface';
export * from './favouriteCarEndpoint.service';
import { FavouriteCarEndpointService } from './favouriteCarEndpoint.service';
export * from './favouriteCarEndpoint.serviceInterface';
export * from './imageEndpoint.service';
import { ImageEndpointService } from './imageEndpoint.service';
export * from './imageEndpoint.serviceInterface';
export * from './locationEndpoint.service';
import { LocationEndpointService } from './locationEndpoint.service';
export * from './locationEndpoint.serviceInterface';
export * from './notificationEndpoint.service';
import { NotificationEndpointService } from './notificationEndpoint.service';
export * from './notificationEndpoint.serviceInterface';
export * from './ratingEndpoint.service';
import { RatingEndpointService } from './ratingEndpoint.service';
export * from './ratingEndpoint.serviceInterface';
export * from './subscriptionEndpoint.service';
import { SubscriptionEndpointService } from './subscriptionEndpoint.service';
export * from './subscriptionEndpoint.serviceInterface';
export * from './termsAndConditionsEndpoint.service';
import { TermsAndConditionsEndpointService } from './termsAndConditionsEndpoint.service';
export * from './termsAndConditionsEndpoint.serviceInterface';
export * from './userEndpoint.service';
import { UserEndpointService } from './userEndpoint.service';
export * from './userEndpoint.serviceInterface';
export const APIS = [BookingEndpointService, BusinessEndpointService, CarEndpointService, CarLocationEndpointService, FavouriteBusinessEndpointService, FavouriteCarEndpointService, ImageEndpointService, LocationEndpointService, NotificationEndpointService, RatingEndpointService, SubscriptionEndpointService, TermsAndConditionsEndpointService, UserEndpointService];
