/**
 * car_rental_backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Booking } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface BookingEndpointServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     */
    bookingsAllGet(extraHttpRequestParams?: any): Observable<Array<Booking>>;

    /**
     * 
     * 
     * @param carId 
     */
    bookingsCarCarIdGet(carId: number, extraHttpRequestParams?: any): Observable<Array<Booking>>;

    /**
     * 
     * 
     * @param carId 
     * @param userId 
     * @param booking 
     */
    bookingsCreatePost(carId?: number, userId?: number, booking?: Booking, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    bookingsGetIdGet(id: number, extraHttpRequestParams?: any): Observable<Booking>;

    /**
     * 
     * 
     * @param id 
     */
    bookingsIdDelete(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param booking 
     */
    bookingsUpdatePut(booking?: Booking, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param userId 
     */
    bookingsUserUserIdGet(userId: number, extraHttpRequestParams?: any): Observable<Array<Booking>>;

}
