/**
 * car_rental_backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Car } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface CarEndpointServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     */
    carsAllGet(extraHttpRequestParams?: any): Observable<Array<Car>>;

    /**
     * 
     * 
     * @param car 
     */
    carsCreatePost(car?: Car, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    carsDeleteIdDelete(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    carsGetIdGet(id: number, extraHttpRequestParams?: any): Observable<Car>;

    /**
     * 
     * 
     * @param car 
     */
    carsUpdatePut(car?: Car, extraHttpRequestParams?: any): Observable<{}>;

}
