/**
 * car_rental_backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Car } from '../model/models';
import { Rating } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface RatingEndpointServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     */
    ratingsAllGet(extraHttpRequestParams?: any): Observable<Array<Rating>>;

    /**
     * 
     * 
     * @param carId 
     */
    ratingsCarCarIdGet(carId: number, extraHttpRequestParams?: any): Observable<Array<Rating>>;

    /**
     * 
     * 
     * @param bookingId 
     * @param carId 
     * @param userId 
     * @param rating 
     */
    ratingsCreatePost(bookingId?: number, carId?: number, userId?: number, rating?: Rating, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    ratingsGetIdGet(id: number, extraHttpRequestParams?: any): Observable<Car>;

    /**
     * 
     * 
     * @param id 
     */
    ratingsIdDelete(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param rating 
     */
    ratingsUpdatePut(rating?: Rating, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param userId 
     */
    ratingsUserUserIdGet(userId: number, extraHttpRequestParams?: any): Observable<Array<Rating>>;

}
