/**
 * car_rental_backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { LoginRequest } from '../model/models';
import { LoginResponse } from '../model/models';
import { User } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface UserEndpointServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param loginRequest 
     */
    userLoginPost(loginRequest?: LoginRequest, extraHttpRequestParams?: any): Observable<LoginResponse>;

    /**
     * 
     * 
     * @param user 
     */
    userSignUpPost(user?: User, extraHttpRequestParams?: any): Observable<{}>;

}
